export const config = {
    SPIN_DEGREES : 90,
    FRAMES : 32,

    COIN_HEIGHT_FROM_BOTTOM : 78,
    OBSTICLE_HEIGHT_FROM_BOTTOM : 38,

    COIN_SCORE_INCREAMENT : 100,
    JUMP_OVER_CONE_SCORE_INCREAMENT : 10,

    COLLISION_WITH_X : 2.1,
    COLLISION_WITH_Y : 1.1,
    SIZE_COLLISION : 1 
}

